config/routes.rb
Rails.application.routes.draw do
  root 'pages#welcome'
  get '/portfolio' => 'pages#portfolio'
  get '/about' => 'pages#about'
  get '/contact' => 'pages#contact'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def welcome
  end
  def portfolio
  end
  def about
  end
  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Portfolio</title>
  <link href='https://fonts.googleapis.com/css?family=Roboto:100,300,500,700' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <script>jQuery(document).ready(function($) {
			$('.banner').unslider();
		});</script>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="header"> 
  <div class="container"> 
    <div class="row"> 
      <div class="menu col-xs-8">
        <ul> 
          <li><%= link_to "Welcome", root_path %></li> 
          <li><%= link_to "Portfolio", portfolio_path %></li> 
          <li><a href="https://medium.com/about-codecademy">Blog</a></li>
          <li><%= link_to "About", about_path %></li>
          <li><%= link_to "Contact", contact_path %></li> 
        </ul> 
      </div> 
      <div class="name col-xs-4"> 
        <h1>Neil Padgett</h1> 
      </div> 
    </div> 
  </div>
</div>

<%= yield %>
  
<div class="footer"> 
  <div class="container"> 
    <ul class="social_media"> 
      <li><a class="github" href="#">github</a></li> 
      <li><a class="linkedin" href="#">linkedin</a></li> 
      <li><a class="twitter" href="#">twitter</a></li> 
    </ul> 
    <p>&copy; 2016 Neil Padgett</p> 
  </div> 
</div>
</body>
</html>

app/views/pages/about.html.erb
<div class="main about"> 
  <div class="container"> 
    <div class="row"> 
      <div class="col-md-6 thumbnail"> 
        <img alt="Me" src="https://dl.dropboxusercontent.com/u/1098200/codecademy/face.jpg" /> 
      </div> 
      <div class="col-md-6"> 
        <h2>Hello. My name is <span class="highlight">Matt Healy</span></h2> 
        <p>I was born in 1975 in London and raised in Newcastle and Northumberland before moving to Macclesfield at 10. Dropped out and worked around from 16 on.</p> 								<p>Since 2001, I've been pursuing my passion, building websites and developing my creativity.</p> 
      </div> 
    </div> 
  </div> 
</div>

app/views/pages/contact.html.erb
<div class="main contact"> 
  <div class="container"> 
    <h2>Contact me</h2> 
    <div class="row"> 
      <div class="col-md-2"> 
        <a class="linkedin" href="#">linkedin</a> 
      </div> 
      <div class="col-md-2"> 
        <a class="github" href="#">github</a> 
      </div> 
      <div class="col-md-2"> 
        <a class="twitter" href="#">twitter</a> 
      </div> 
      <div class="col-md-2"> 
        <a class="facebook" href="#">facebook</a> 
      </div> 
      <div class="col-md-2"> 
        <a class="gplus" href="#">google plus</a> 
      </div> 
      <div class="col-md-2"> 
        <a class="instagram" href="#">instagram</a> 
      </div> 
    </div> 
  </div> 
</div>

app/views/pages/portfolio.html.erb
<div class="main portfolio"> 
  <div class="jumbotron slideshow"> 
    <div class="slideshow-container banner unslider unslider-wrap"> 
      <ul class="unslider-carousel">
      <li class="slide"> 
        <img alt="Slide01" src="https://dl.dropboxusercontent.com/u/1098200/codecademy/eagle.jpeg" /> 
      </li> 
      <li class="slide"> 
        <img alt="Slide02" src="https://dl.dropboxusercontent.com/u/1098200/codecademy/bike.jpeg" /> 
      </li> 
      <li class="slide"> 
        <img alt="Slide03" src="https://dl.dropboxusercontent.com/u/1098200/codecademy/bear.jpeg" /> 
      </li>
      </ul>
    </div> 
  </div> 
  <div class="container"> 
    <div class="row"> 
      <a class="col-md-6 project" href="#"> 
        <div class="thumbnail-header"> 
          <div class="thumbnail-header-btn"></div> 
          <div class="thumbnail-header-btn"></div> 
          <div class="thumbnail-header-btn"></div> 
        </div> 
        <div class="thumbnail"> 
          <img alt="Project01" src="https://dl.dropboxusercontent.com/u/1098200/codecademy/portfolioPics/project01.jpg" /> 
        </div> 
        <h3>TravelGos Booking App</h3> 
        <p>NGO liberal change-makers global time of extraordinary change, prevention climate change mobilize shift. Communities, social movement United Nations, Oxfam planned giving Global South humanitarian. Maximize.</p> 
      </a> 
      <a class="col-md-6 project" href="#"> 
        <div class="thumbnail-header"> 
          <div class="thumbnail-header-btn"></div> 
          <div class="thumbnail-header-btn"></div> 
          <div class="thumbnail-header-btn"></div> 
        </div> 
        <div class="thumbnail"> 
          <img alt="Project02" src="https://dl.dropboxusercontent.com/u/1098200/codecademy/portfolioPics/project02.jpg" /> 
        </div> 
        <h3>Breathers Reservation Site</h3> 
        <p>Pursue these aspirations free-speech healthcare sharing economy freedom. Beneficiaries gender rights raise awareness change movements provide. Eradicate, diversification inspire breakthroughs, incubation; solve Peace Corps. Innovate.</p> 
      </a> 
    </div> 
    <div class="row"> 
      <a class="col-md-6 project" href="#"> 
        <div class="thumbnail-header"> 
          <div class="thumbnail-header-btn"></div> 
          <div class="thumbnail-header-btn"></div> 
          <div class="thumbnail-header-btn"></div> 
        </div> 
        <div class="thumbnail"> 
          <img alt="Project03" src="https://dl.dropboxusercontent.com/u/1098200/codecademy/portfolioPics/project03.jpg" /> 
        </div> 
        <h3>EnVogue Events Portfolio</h3> 
        <p>Informal economies; underprivileged, grantees transformative prosperity. Education best practices connect achieve plumpy'nut. Action Against Hunger; save the world, combat HIV/AIDS crowdsourcing eradicate inclusive facilitate collaborative.</p> 
      </a> 
      <a class="col-md-6 project" href="#"> 
        <div class="thumbnail-header"> 
          <div class="thumbnail-header-btn"></div> 
          <div class="thumbnail-header-btn"></div> 
          <div class="thumbnail-header-btn"></div> 
        </div> 
        <div class="thumbnail"> 
          <img alt="Project04" src="https://dl.dropboxusercontent.com/u/1098200/codecademy/portfolioPics/project04.jpg" /> 
        </div> 
        <h3>Gauntlet Gallery</h3> 
        <p>Small-scale farmers; collaborative cities Bill and Melinda Gates best practices equity health theory of social change human experience. Tackle rural development relief worldwide respect, economic.</p> 
      </a> 
    </div> 
    <div class="row"> 
      <a class="col-md-6 project" href="#"> 
        <div class="thumbnail-header"> 
          <div class="thumbnail-header-btn"></div> 
          <div class="thumbnail-header-btn"></div> 
          <div class="thumbnail-header-btn"></div> 
        </div> 
        <div class="thumbnail"> 
          <img alt="Project05" src="https://dl.dropboxusercontent.com/u/1098200/codecademy/portfolioPics/project05.jpg" /> 
        </div> 
        <h3>Koi Pond Online Visitors Guide</h3> 
        <p>UNICEF, research Ford Foundation outcomes collaborative consumption turmoil change lives. Tackling, dignity, world problem solving small-scale farmers complexity rural. Emergent humanitarian, necessities effect, challenges of.</p> 
      </a> 
      <a class="col-md-6 project" href="#"> 
        <div class="thumbnail-header"> 
          <div class="thumbnail-header-btn"></div> 
          <div class="thumbnail-header-btn"></div> 
          <div class="thumbnail-header-btn"></div> 
        </div> 
        <div class="thumbnail"> 
          <img alt="Project06" src="https://dl.dropboxusercontent.com/u/1098200/codecademy/portfolioPics/project06.jpg" /> 
        </div> 
        <h3>Academy of Sciences  Newsletter</h3> 
        <p>Aid collaborative global network overcome injustice honesty measures. Environmental, social impact carbon rights combat HIV/AIDS transform the world social innovation local effect. Free expression committed.</p> 
      </a> 
    </div> 
  </div> 
</div>

app/views/pages/welcome.html.erb
<div class="main home">
  <div class="jumbotron"> 
    <div class="container">
      <h2>Hello. My name is <span class="highlight">Neil Padgett</span> and I have creative ideas and build websites</h2>
      <%= link_to "View my work", portfolio_path, class:"btn right" %>
    </div> 
  </div>
</div> 